In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.graphics.correlation as smc
import statsmodels.graphics.gofplots as smg
import statsmodels.stats.api as sms
from statsmodels.stats.outliers_influence import OLSInfluence

In [4]:
# Read the data
environmental_indicators = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/regression_sprint/enviro_indicators.csv', index_col=0)
environmental_indicators.head(10)

,forest_coverage,biodiversity_index,protected_areas,deforestation_rate,carbon_sequestration,soil_erosion,land_degradation,rural_population,population_density
Country,,,,,,,,,
Vietnam,36.217808,6.505159,14.832708,36.583106,53.128459,7.987880,55.020903,35.912142,468.715839
Guinea-Bissau,76.550001,94.888554,23.994363,123.384939,279.836286,13.013811,41.655073,34.639379,351.054600
Bosnia and Herzegovina,61.239576,96.563203,9.932348,115.743745,237.834951,13.037065,26.951490,78.380633,289.329973
Lesotho,51.906094,80.839735,33.076894,111.752369,149.948515,11.179719,27.460479,43.585863,57.616482
Indonesia,20.921305,30.461377,7.609273,46.450326,103.939415,2.715506,46.297784,73.522793,311.353541
Singapore,20.919616,9.767211,39.541043,25.249501,201.926827,16.870747,54.855513,57.868318,495.126387
Saint Lucia,14.065853,68.423303,32.028567,76.130581,474.309367,7.094821,54.354321,67.688678,78.641167
Turkmenistan,70.632330,44.015249,11.955049,73.358093,195.441319,4.543852,48.993777,50.158226,263.981530
Kenya,52.078051,12.203823,5.193274,36.843972,283.455780,1.774728,42.101582,54.614233,439.912805
United States,59.565080,49.517691,33.541150,81.512031,366.358532,12.226966,14.206998,49.551062,372.976623

In [7]:
environmental_indicators.shape

(32, 9)

In [8]:
environmental_indicators.head()

,forest_coverage,biodiversity_index,protected_areas,deforestation_rate,carbon_sequestration,soil_erosion,land_degradation,rural_population,population_density
Country,,,,,,,,,
Vietnam,36.217808,6.505159,14.832708,36.583106,53.128459,7.987880,55.020903,35.912142,468.715839
Guinea-Bissau,76.550001,94.888554,23.994363,123.384939,279.836286,13.013811,41.655073,34.639379,351.054600
Bosnia and Herzegovina,61.239576,96.563203,9.932348,115.743745,237.834951,13.037065,26.951490,78.380633,289.329973
Lesotho,51.906094,80.839735,33.076894,111.752369,149.948515,11.179719,27.460479,43.585863,57.616482
Indonesia,20.921305,30.461377,7.609273,46.450326,103.939415,2.715506,46.297784,73.522793,311.353541

In [9]:
environmental_indicators.isna().sum()

forest_coverage         0
biodiversity_index      0
protected_areas         0
deforestation_rate      0
carbon_sequestration    0
soil_erosion            0
land_degradation        0
rural_population        0
population_density      0
dtype: int64

In [10]:
environmental_indicators.describe()

,forest_coverage,biodiversity_index,protected_areas,deforestation_rate,carbon_sequestration,soil_erosion,land_degradation,rural_population,population_density
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,40.484972,49.873676,22.542576,69.063387,255.649653,9.874722,35.263996,53.223641,299.594850
std,19.529573,32.201278,10.338851,30.100259,132.047729,5.464372,14.555348,18.552335,129.851023
min,11.440915,3.438852,5.193274,18.113759,53.128459,1.315169,10.253079,20.927397,27.611714
25%,22.810674,24.308070,14.113293,46.131162,158.644367,5.113528,21.700207,37.461786,227.116183
50%,38.226980,46.766470,24.319532,70.838794,225.734136,10.896565,40.988263,51.783151,319.917934
75%,52.603530,81.348239,31.716570,90.632026,355.935380,13.623203,45.781167,71.766124,402.520220
max,77.893690,96.958463,39.541043,128.118420,493.542704,18.797870,55.020903,78.380633,495.126387

In [12]:
numerical_columns=environmental_indicators.select_dtypes(include=[np.number])

In [14]:
correlation_matrix=numerical_columns.corr()
correlation_matrix

,forest_coverage,biodiversity_index,protected_areas,deforestation_rate,carbon_sequestration,soil_erosion,land_degradation,rural_population,population_density
forest_coverage,1.000000,0.274022,0.108666,0.556136,0.053950,-0.109275,0.154287,0.022843,0.027884
biodiversity_index,0.274022,1.000000,-0.067212,0.922463,0.009418,-0.062205,-0.136184,0.042478,-0.135042
protected_areas,0.108666,-0.067212,1.000000,0.120202,0.146215,0.321587,-0.113558,0.172193,-0.001360
deforestation_rate,0.556136,0.922463,0.120202,1.000000,0.063443,-0.082024,-0.092885,0.105760,-0.126157
carbon_sequestration,0.053950,0.009418,0.146215,0.063443,1.000000,0.237919,0.268428,-0.017830,-0.344947
soil_erosion,-0.109275,-0.062205,0.321587,-0.082024,0.237919,1.000000,-0.110673,0.146636,0.046528
land_degradation,0.154287,-0.136184,-0.113558,-0.092885,0.268428,-0.110673,1.000000,-0.085273,-0.137509
rural_population,0.022843,0.042478,0.172193,0.105760,-0.017830,0.146636,-0.085273,1.000000,0.226600
population_density,0.027884,-0.135042,-0.001360,-0.126157,-0.344947,0.046528,-0.137509,0.226600,1.000000